### ISSUE TITLE
different awsTag / AssociateTag for different webservices 

### ISSUE THREAD

**Issue by po-ro** [cmincarelli/amazon-affiliate-api#6]
Hi,

thank you for the great work and letting us all reuse your coding!

As fas as I understood the localization of amazon services is not only separated by the webservice itself, but also by the 'AssociateTag' used. This is especially important when querying multiple webservices after another. 

So the request I am making is to move the 'AssociateTag' out of the credentials/config and add it as parameter to the query itself.

Thank you already in advance!

**Comment by cmincarelli** [comment]
Feel free to submit a PR

**Comment by cmincarelli** [comment]
Thanks, I've merged the request and will close the issue.
